[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3338"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false 